server:
  port: 9003

spring:
  data:
    mongodb:
      uri: mongodb+srv://user1:user@cluster0.6lihh.mongodb.net/CarWash?retryWrites=true&w=majority
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name : Order-Service
