server:
  port: 9001

spring:
  data:
    mongodb:
      uri: mongodb+srv://user1:user@cluster0.6lihh.mongodb.net/CarWashAdmin?retryWrites=true&w=majority
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name : Admin-Service


logging:
  file:
    name: applications.log