server:
  port: 9002

spring:
  data:
    mongodb:
      uri: mongodb+srv://user1:user@cluster0.6lihh.mongodb.net/CarWashWasher?retryWrites=true&w=majority
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name : Washer-Service
